import { image } from "framer-motion/client";

const events = [
  {
    id: 1,
    year: '2025-26',
    name: 'Clockout 3.0',
    description: 'CLOCKOUT 3.0 | Shadows of Bhangarh: An immersive, story-driven event combining mystery, teamwork, and problem-solving. Featuring three dynamic rounds— The Initiation, The Investigation, and The Hunt .participants collaborated across years in AI-themed factions to solve puzzles, analyze clues, and compete in a campus-wide treasure hunt. A perfect blend of creativity, strategy, and excitement.',
    image: '/Clockout3.0/clockout3_cover.jpg', 
    image1: '/Clockout3.0/clockout3_1.jpg', 
    image2: '/Clockout3.0/clockout3_2.jpg', 
    image3: '/Clockout3.0/clockout3_3.jpg', 
    image4: '/Clockout3.0/clockout3_4.jpg', 
    image5: '/Clockout3.0/clockout3_5.jpg',  
    image6: '/Clockout3.0/clockout3_6.jpg',
    },  
    {id: 2,
    year: '2024-25', 
    name: 'Clockout 2.0',
    description: 'A major event focusing on innovation and technology.',
    image: '/Clockout2.0/co2_1.jpg',
    image1: '/Clockout2.0/co2_5.jpg',
    image2: '/Clockout2.0/co2_1.jpg',
    image3: '/Clockout2.0/co2_2.jpg',
    image4: '/Clockout2.0/co2_3.jpg',
    image5: '/Clockout2.0/co2_6.jpg',
    image6: '/Clockout2.0/co2_4.jpg',

    },
    { id: 3,
    year: '2024-25',    
    name: 'Synergy 2.0',
    description: 'An event that brings together diverse minds for collaboration.',
    image: '/Synergy2.0/synergy2_1.jpg',
    image1: '/Synergy2.0/synergy2_core.jpg',
    image2: '/Synergy2.0/Synergy_winner.jpg',
    image3: '/Synergy2.0/Synergy.jpg',
    image4:'/Synergy2.0/synergy2_group.jpg',
    image5:'/Synergy2.0/synergy2_inaugration.jpg',
    image6:'/Synergy2.0/synergy2_6.jpg',
    
    },
    { id: 4,
    year: '2024-25',
    name: 'Seminar',
    description: 'A seminar featuring industry experts and thought leaders.',
    image: '/seminar/4.jpg',
    image1: '/seminar/IMG_5281.jpeg',
    image2:'/seminar/1.jpg',
    image3:'/seminar/2.jpg',
    image4:'/seminar/3.jpg',
    image5:'/seminar/4.jpg',
    image6:'/seminar/5.jpg',
    },
    { id: 5,
    year: '2023-24',
    name: 'Clockout 1.0',
    description: 'The inaugural event focusing on emerging technologies.',
    image: '/clockout1.0.png',
    },
    { id: 6,
    year: '2023-24',
    name: 'Synergy 1.0',
    description: 'The first synergy event aimed at fostering collaboration.',
    image: '/synergy1.0.png',
    },
    { id: 7,
    year: '2023-24',
    name: 'Seminar',
    description: 'A seminar that discusses the latest trends in the industry.',
    image: '/seminar1.png',
    },
        
  ];

  export default events;